export { default as Home } from "./home";
export { default as Cart } from "./cart";
export { default as Checkout } from "./checkout";
export { default as Orders } from "./orders";
export { default as Thankyou } from "./thankyou";
export { default as Profile } from "./profile";
export { default as AdminLogin } from "./admin/Login";
export { default as AdminDashboard } from "./admin//dashboard";
export { default as AdminOrders } from "./admin/orders";
